### ISSUE TITLE
Byzantium changes

### ISSUE THREAD

**Issue by pirapira** [ethereum/yellowpaper#229]
We can check these boxes when we create PRs for the yellow paper, or the EIPs are dropped from Metropolis.

* [x] <del>[EIP 5/8](https://github.com/ethereum/EIPs/issues/8)</del> https://github.com/ethereum/EIPs/pull/211 (RETURNDATACOPY and RETURNDATASIZE) | #264 
* [x] [EIP 86](https://github.com/ethereum/EIPs/pull/208) to be followed in #231 (initial abstraction changes) | #277
* [x] [EIP 96](https://github.com/ethereum/EIPs/pull/210) (block hash in a special contract) | https://github.com/ethereum/yellowpaper/pull/311
* [x] [EIP 98](https://github.com/ethereum/EIPs/pull/658) remove medstate from transaction receipts | already in `metropolis` branch
* [x] [EIP 100](https://github.com/ethereum/EIPs/issues/100) (difficulty adjustment) (equation (43).  2017-02-17: two options still; 2017-03-02 perhaps option 1(b)) to be followed in #253 | #266 
* [x] <del>[EIP 101](https://github.com/ethereum/EIPs/issues/101)</del> [EIP 198](https://github.com/ethereum/EIPs/pull/198) (Big-int precompiles) to be followed in #235 | #268 
* [x] <del>[EIP 116](https://github.com/ethereum/EIPs/issues/116)</del> https://github.com/ethereum/EIPs/pull/214 (STATIC_CALL) to be followed in #234 | #270 
* [x] <del>[EIP 166](https://github.com/ethereum/EIPs/issues/166) replay protection with higher-order bits of nonce, to be tracked in #259</del>
* [x] EIP <del>[196](https://github.com/ethereum/EIPs/issues/196)</del> https://github.com/ethereum/EIPs/pull/213 & <del>[197](https://github.com/ethereum/EIPs/issues/197) </del> https://github.com/ethereum/EIPs/pull/212 (zkSNARK verification primitives) | https://github.com/ethereum/yellowpaper/pull/297
* [x] EIP [206](https://github.com/ethereum/EIPs/pull/206) (REVERT) to be followed in https://github.com/ethereum/yellowpaper/issues/232 | #278 
* [x] EIP [649](https://github.com/ethereum/EIPs/pull/669) | https://github.com/ethereum/yellowpaper/pull/333
* [x] EIP [658](https://github.com/ethereum/EIPs/pull/658/files) (add status code in receipts) | https://github.com/ethereum/yellowpaper/pull/318

This list initially followed https://github.com/ethereum/pm/issues/4

**Comment by VoR0220** [comment]
Will https://github.com/ethereum/EIPs/issues/116 be included in there? Or no?

**Comment by pirapira** [comment]
I added it.

**Comment by VoR0220** [comment]
awesome. I shall share this list so that Monax team can be aware too...these are all scheduled to be included, yes?

**Comment by pirapira** [comment]
Probably, a few points have already been overwritten by something else.  I'm just adding everything that might be coming.

**Comment by tawaren** [comment]
Is their any plan to include a byte code versioning scheme like #154 in Metropolis?

**Comment by pirapira** [comment]
A branch `metropolis` was created in this repository.

**Comment by 5chdn** [comment]
[EIP-649](https://github.com/ethereum/EIPs/pull/669) is missing from the list. :point_up:

**Comment by pirapira** [comment]
@5chdn I added it.

**Comment by bbuenz** [comment]
Why aren't ECPoints stored in their compressed form which is half the size? That is use just x + 1 bit instead of x,y?

**Comment by rmercer93** [comment]
@bbuenz within the evm even the cost of storing 32 bytes is lower than the cost of recomputing y from a given x (or at least it definitely was up until the modexp precompile was added -- unsure about now, i'll benchmark it if u want). for txns the public key is recovered from the signature rather than sent alongside it so i assume you're asking about precompile justification?

**Comment by bbuenz** [comment]
Shouldn't the precompile cost be based on real world costs? I think Pieter Wuille said that in libsec256k1 group exponentiation is 1% more expensive which should be offset by the storage savings, shouldn't it?

**Comment by pirapira** [comment]
@bbuenz the gas costs across EVM are not accurate enough to make 1%  calibration meaningful.

**Comment by bbuenz** [comment]
@pirapira I don't think I explained myself well enough. Using point compression, i.e. 32 byte eliptic curve points makes addition and multiplication just 1% slower. So you get 50% storage/communication improvement for just 1% computation loss. That seems like a clear win to me.

**Comment by pirapira** [comment]
This has been done.  Thans @gavofyork for the license and thanks @nicksavers for the merges.
