### ISSUE TITLE
Parent issue for all updates of uncle logic / validation

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/yellowpaper#82]
@vbuterin @gavofyork Please review / edit the below as necessary.

- [x] Change uncle reward from 15/16 to X/Y ?
- [x] Change maximum number of uncles allowed per block to 2?
- [x] Change uncle reward logic to depend on Nth generation? I.e., miner only receives full uncle reward after uncle header inclusion in N consecutive blocks.
- [x] While the uncle uniqueness is technically defined as the uncles are defined as a set, this could be clarified with a short explicit mention.
